#!/usr/bin/env bash
# Install hskctl and the Omarchy plugin for the current user.
#
#   ./install.sh            # install everything
#   ./install.sh --udev     # (re)generate the udev rule from a probe
#   ./install.sh --uninstall
#
# Nothing here needs root except the udev rule, which is prompted for
# separately so the rest of the install stays unprivileged.

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN_DIR="${XDG_BIN_HOME:-$HOME/.local/bin}"
SHARE_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/hskctl"
PROFILE_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/hskctl/profiles"
PLUGIN_ID="io.github.keasbeexd.hsk"
PLUGIN_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/omarchy/plugins/$PLUGIN_ID"
UDEV_RULE="/etc/udev/rules.d/60-gwolves-hsk.rules"

info() { printf '\033[1m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[33m warn:\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[31merror:\033[0m %s\n' "$*" >&2; exit 1; }

install_cli() {
  info "Installing hskctl to $BIN_DIR"
  mkdir -p "$BIN_DIR" "$SHARE_DIR" "$PROFILE_DIR"
  rm -rf "$SHARE_DIR/hskctl"
  cp -r "$REPO_DIR/hskctl" "$SHARE_DIR/hskctl"
  cp -r "$REPO_DIR/tools" "$SHARE_DIR/tools"

  # Profiles are copied to config, not share: the whole point is that the user
  # edits them as the protocol gets decoded. An existing profile is never
  # clobbered -- that would throw away decoding work.
  for profile in "$REPO_DIR"/profiles/*.json; do
    local name
    name="$(basename "$profile")"
    if [[ -e "$PROFILE_DIR/$name" ]]; then
      warn "keeping your existing $PROFILE_DIR/$name (shipped copy at $profile)"
    else
      cp "$profile" "$PROFILE_DIR/$name"
    fi
  done

  cat > "$BIN_DIR/hskctl" <<EOF
#!/usr/bin/env bash
exec python3 -c 'import sys; sys.path.insert(0, "$SHARE_DIR"); from hskctl.cli import main; sys.exit(main())' "\$@"
EOF
  chmod +x "$BIN_DIR/hskctl"

  if ! command -v hskctl >/dev/null 2>&1; then
    warn "$BIN_DIR is not on your PATH -- add it, or set the plugin's 'Path to hskctl' setting to $BIN_DIR/hskctl"
  fi
}

install_plugin() {
  info "Installing the Omarchy plugin to $PLUGIN_DIR"
  mkdir -p "$PLUGIN_DIR"
  cp "$REPO_DIR/plugin/$PLUGIN_ID"/* "$PLUGIN_DIR/"

  if command -v omarchy-shell >/dev/null 2>&1; then
    info "Rescanning plugins"
    omarchy-shell shell rescanPlugins >/dev/null 2>&1 || warn "rescan failed -- is the shell running?"
    info "Enable it with:  omarchy plugin enable $PLUGIN_ID"
  else
    warn "omarchy-shell not found; run 'omarchy-shell shell rescanPlugins' yourself"
  fi
}

install_udev() {
  info "Working out which device to grant access to"
  local probe vid
  probe="$("$BIN_DIR/hskctl" --json probe 2>/dev/null || echo '{}')"
  vid="$(python3 - "$probe" <<'PY'
import json, sys
try:
    data = json.loads(sys.argv[1])
except Exception:
    data = {}
candidates = data.get("candidates") or []
print(candidates[0]["vendorId"] if candidates else "")
PY
)"

  if [[ -z "$vid" ]]; then
    warn "No candidate device found. Plug the mouse (or its dongle) in and re-run:"
    warn "  ./install.sh --udev"
    return
  fi

  info "Granting your user access to hidraw devices with vendor id $vid"
  local tmp
  tmp="$(mktemp)"
  cat > "$tmp" <<EOF
# G-Wolves HSK -- let the desktop user read and write the config endpoint
# without sudo. Generated by omarchy-hsk install.sh.
KERNEL=="hidraw*", ATTRS{idVendor}=="$vid", MODE="0660", TAG+="uaccess"
EOF
  echo
  cat "$tmp"
  echo
  read -r -p "Write this to $UDEV_RULE (needs sudo)? [y/N] " reply
  if [[ "$reply" =~ ^[Yy] ]]; then
    sudo install -m 0644 "$tmp" "$UDEV_RULE"
    sudo udevadm control --reload-rules
    sudo udevadm trigger
    info "Rule installed. Unplug and replug the mouse or dongle."
  else
    info "Skipped. Without it hskctl needs sudo to write settings."
  fi
  rm -f "$tmp"
}

uninstall() {
  info "Removing hskctl and the plugin"
  rm -f "$BIN_DIR/hskctl"
  rm -rf "$SHARE_DIR" "$PLUGIN_DIR"
  info "Left in place: $PROFILE_DIR (your decoded protocol work)"
  info "Left in place: $UDEV_RULE (remove with sudo if you want)"
  command -v omarchy-shell >/dev/null 2>&1 && omarchy-shell shell rescanPlugins >/dev/null 2>&1 || true
}

case "${1:-}" in
  --uninstall) uninstall ;;
  --udev)      install_udev ;;
  "")
    command -v python3 >/dev/null || die "python3 is required"
    install_cli
    install_plugin
    install_udev
    echo
    info "Done. Next:"
    echo "     hskctl probe          # find the mouse's config endpoint"
    echo "     hskctl fields         # see what is writable and what needs verifying"
    echo "     omarchy plugin enable $PLUGIN_ID"
    echo
    echo "  docs/PROTOCOL-DISCOVERY.md    Verify the readings against the vendor app before writing:"
    ;;
  *) die "unknown option: $1" ;;
esac
